version: '3.0'
services:
  api:
    container_name: api-container
    restart: always
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file: .env

  client:
    container_name: client-container
    restart: always
    build: ./frontend
    ports:
      - '8080:8080'
    depends_on:
      - api
    env_file: .env

  postgres:
    container_name: postgres
    image: postgres:11.5
    restart: always
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    env_file: .env
